packages: []
lockfile: false
allowBuilds:
  "@karinjs/node-pty": true
  "@karinjs/sqlite3-cjs": true
  canvas: true
  classic-level: true
  protobufjs: true
  puppeteer: true
  sharp: true
  sqlite3: true
  esbuild: true
publicHoistPattern:
  - "*sqlite3*"
  - "*express*"
